AWSTemplateFormatVersion: '2010-09-09'
Description: Simple Web Server with S3

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0ddc798b3f1a5117e # Amazon Linux 2 AMI for N. Virginia (as of the last check)
      SecurityGroups: 
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            yum update -y
            yum install -y nginx
            service nginx start
            echo "<h1>Hello from Nginx</h1>" > /usr/share/nginx/html/index.html
            aws s3 cp s3://my-website-bucket/index.html /usr/share/nginx/html/

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-website-bucket-nikolaos-koulopoulos # Fully lowercase bucket name
      WebsiteConfiguration: # Enables static website hosting
        IndexDocument: index.html
        ErrorDocument: error.html

Outputs:
  WebsiteURL:
    Value: !Sub "http://${WebServerInstance.PublicDnsName}"
    Description: URL of the web server
  S3BucketName:
    Value: my-website-bucket
    Description: S3 bucket for website content
